ai:
  api_url: https://api.groq.com/openai/v1/chat/completions
  max_tokens: 30000
  parallel_models:
  - openrouter/deepseek/deepseek-chat-v3-0324:free
  - openrouter/deepseek/deepseek-chat-v3.1:free
  - openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free
  temperature: 0.3
commit:
  format: conventional
  auto_confirm: false
  scope_detection: true
  issue_detection: true
  breaking_changes: false
  multi_line: true
  max_diff_tokens: 25000
review_merge:
  check_conflicts: true
  show_stats: true
  suggest_actions: true
  analyze_breaking_changes: true
  max_commits_to_analyze: 50
  max_tokens: 25000
diff:
  summary_style: detailed
  show_file_stats: true
  detect_patterns: true
  max_files_to_analyze: 100
  max_tokens: 25000
general:
  language: en
  verbose: false
  stats_tracking: true
stats:
  use_db: true
  backend: sqlite
  db_path: null
models:
  exclude_keywords:
  - whisper
  - tts
  - playai
  - distil-whisper
ollama:
  base_url: http://localhost:11434
  endpoints:
    local: http://localhost:11434
    remote: https://ollama.int.the.yaml.life
anannas:
  api_url: https://api.anannas.ai/v1/chat/completions
openrouter:
  api_url: https://openrouter.ai/api/v1/chat/completions
